# Inherited Methods
kCreate: 0        # 0
kDestroy: 1       # 1
kNodeFailure: -1  # 2
kRecover: -1      # 3
kMigrate: -1      # 4
kUpdate: -1       # 5

# Custom Methods
kCreateContainer: 10
kDestroyContainer: 11
kRegisterModule: 12
kDestroyModule: 13
kUpgradeModule: 14
kGetPoolId: 15
kStopRuntime: 16
kSetWorkOrchQueuePolicy: 17
kSetWorkOrchProcPolicy: 18
kFlush: 19
kGetDomainSize: 20
kUpdateDomain: 21